export default {
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SHOW_SIGN_IN: 'SHOW_SIGN_IN',
  HIDE_SIGN_IN: 'HIDE_SIGN_IN',
  SHOW_SIGN_UP: 'SHOW_SIGN_UP',
  HIDE_SIGN_UP: 'HIDE_SIGN_UP',
  SET_SIGN_IN_INFO: 'SET_SIGN_IN_INFO'
}
